name = "CutCellMesh"
uuid = "24df4ea3-ebf2-4a26-8fd2-c05fb361f768"
authors = ["Fastaxx <Fastaxx@github.com>"]
version = "0.1.0"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
